version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Use the desired Node.js version
    commands:
      - npm install  # Install project dependencies

  build:
    commands:
      - npm run build  # Replace with your build script/command
      - npm run test   # Replace with your test script/command

artifacts:
  files: '**/*'  # Include all files in the build artifact
